# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - newsagg-func

on:
  workflow_run:
    workflows:
      - Build and deploy ASP.Net Core app to Azure Web App - newsagg-web
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: azure-newsagg-${{ github.ref }}
  cancel-in-progress: true

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: functionapp
  PYTHON_VERSION: '3.13'

jobs:
  build:
    if: >-
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: functionapp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python version
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Zip artifact for deployment
        run: zip -r ../release.zip . -x 'venv/*'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip -d functionapp
          rm release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_04B98E97454146D88FE18C8304E718B3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A1705BCD3CB645B5A9BCEF34AE8E3294 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8102D7E9228544DA8D6C857538331779 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'newsagg-func'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
